# Ruby CircleCI 2.0 configuration file
# Ruby CircleCI 2.0 の構造ファイル
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
# より多くの詳細は URL をチェック
# version で重大な変更についての警告を出している（CircleCI のバージョン）
version: 2
# ジョブを1つしか定義しない場合は名前を build にする
jobs:
  build:
    # ジョブを実行する環境を machine, macos docker から選ぶ（この場合は docker）
    docker:
    # specify the version you desire here
    # ruby のバージョンと node と browsers サフィックスをつけている
    - image: circleci/ruby:2.5.3-node-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    # steps を実行するディレクトリを指定
    working_directory: ~/stock-links

    # steps をキーにして実行したいコマンドを1つ以上定義する
    steps:
      # リポジトリのコードのチェックアウトを行う特殊ステップ
    - checkout

    # Download and cache dependencies
    # key で指定されたキャッシュを復元する
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Configure Bundler
        command: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler

    - run:
        # ステップのタイトル
        name: install dependencies
        # --jobs=4 で並列実行、--retry=3 で失敗したときリトライする回数、--path で vendor/bundle に bundle install する
        command: bundle install --jobs=4 --retry=3 --path vendor/bundle

    # gem をキャッシュできる
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: rails db:create
    - run: rails db:schema:load

    # run tests!
    - run:
        name: run tests
        command: rails test

    # collect reports
    - store_test_results:
        path: test/reports/
